version: '3'

services:
  db:
    image: mariadb:10.5
    restart: unless-stopped
    container_name: nxtclouddb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - <localfilefolder>:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<enter a password>
      - MYSQL_PASSWORD=<enter a password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud


  app:
    image: nextcloud
    container_name: nxtcloud
    restart: unless-stopped
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - <localfilefolder>:/var/www/html
    environment:
      - MYSQL_PASSWORD=<enter a password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
